[2024-06-18T03:51:09.693+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T03:51:09.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_stats_v2.check_prev_status manual__2024-06-18T03:51:08.384492+00:00 [queued]>
[2024-06-18T03:51:09.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_stats_v2.check_prev_status manual__2024-06-18T03:51:08.384492+00:00 [queued]>
[2024-06-18T03:51:09.811+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-18T03:51:09.827+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_prev_status> on 2024-06-18 03:51:08.384492+00:00
[2024-06-18T03:51:09.835+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'check_stats_v2', 'check_prev_status', 'manual__2024-06-18T03:51:08.384492+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/skipDAG.py', '--cfg-path', '/tmp/tmp_p_7j9l7']
[2024-06-18T03:51:09.837+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask check_prev_status
[2024-06-18T03:51:09.838+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=636) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T03:51:09.839+0000] {standard_task_runner.py:63} INFO - Started process 637 to run task
[2024-06-18T03:51:09.888+0000] {task_command.py:426} INFO - Running <TaskInstance: check_stats_v2.check_prev_status manual__2024-06-18T03:51:08.384492+00:00 [running]> on host 39ad15fd710d
[2024-06-18T03:51:10.004+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_stats_v2' AIRFLOW_CTX_TASK_ID='check_prev_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T03:51:08.384492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T03:51:08.384492+00:00'
[2024-06-18T03:51:10.006+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T03:51:10.044+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-18T03:51:10.052+0000] {python.py:237} INFO - Done. Returned value was: check_status
[2024-06-18T03:51:10.053+0000] {branch.py:36} INFO - Branch into check_status
[2024-06-18T03:51:10.053+0000] {skipmixin.py:178} INFO - Following branch check_status
[2024-06-18T03:51:10.072+0000] {skipmixin.py:246} INFO - Skipping tasks [('skipped_run', -1)]
[2024-06-18T03:51:10.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T03:51:10.133+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=check_stats_v2, task_id=check_prev_status, run_id=manual__2024-06-18T03:51:08.384492+00:00, execution_date=20240618T035108, start_date=20240618T035109, end_date=20240618T035110
[2024-06-18T03:51:10.179+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T03:51:10.216+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T03:51:10.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
